version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
        environment:
          TZ: "America/New_York"
    working_directory: ~/repo
    environment:
      TZ: "America/New_York"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v0-dependencies-{{ checksum "requirements/prod.txt" }}-{{ checksum "requirements/dev.txt" }}-{{ checksum "requirements/test.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v0-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r ./requirements/dev.txt -r ./requirements/test.txt -r ./requirements/prod.txt

      - save_cache:
          paths:
            - ./venv
          key: v0-dependencies-{{ checksum "requirements/prod.txt" }}-{{ checksum "requirements/dev.txt" }}-{{ checksum "requirements/test.txt" }}

      - run:
          name: Run Tests
          command: |
            ./tools/run_tests.sh 'not integration'

      - run:
          name: Run Pylint
          command: |
            ./tools/run_pylint.sh

      - run:
          name: Run Black
          command: |
            ./tools/run_black.sh

      - run:
          name: Run Isort
          command: |
            ./tools/run_isort.sh

      - run:
          name: Run Mypy
          command: |
            ./tools/run_mypy.sh

